name: Deploy to Firebase

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging

# Define permissions for the workflow
permissions:
  id-token: write  # Required for Firebase deployment
  checks: write    # Required for Firebase deployment status checks
  contents: write  # Required for deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    # github.event.pull_request.merged == true for auto-deploy
    # github.event_name == 'workflow_dispatch' for manual deploy

    if: github.event_name == 'workflow_dispatch'
    environment: ${{ github.event.inputs.environment || 'production' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Create .env file
      run: |
        echo "REACT_APP_FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> .env
        echo "REACT_APP_FIREBASE_AUTH_DOMAIN=${{ secrets.FIREBASE_AUTH_DOMAIN }}" >> .env
        echo "REACT_APP_FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> .env
        echo "REACT_APP_FIREBASE_STORAGE_BUCKET=${{ secrets.FIREBASE_STORAGE_BUCKET }}" >> .env
        echo "REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}" >> .env
        echo "REACT_APP_FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> .env
        echo "REACT_APP_ENABLE_GOOGLE_LOGIN=${{ secrets.ENABLE_GOOGLE_LOGIN }}" >> .env

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        channelId: live
        projectId: '${{ secrets.FIREBASE_PROJECT_ID }}'